### ISSUE TITLE
Torch_xla error when using TPU 

### ISSUE THREAD

**Issue by greenrace66** [jwohlwend/boltz#72] opened 2024-11-30 14:59 UTC
I tried out running boltz on google colab v28 tpu using --accelerator tpu option and get the following error:
![Screenshot_30-11-2024_202332_colab research google com](https://github.com/user-attachments/assets/20ccd333-8c01-4035-941d-57ce6d38ec4e)

/usr/local/lib/python3.10/dist-packages/torch_xla/__init__.py:253: UserWarning: `tensorflow` can conflict with `torch-xla`. Prefer `tensorflow-cpu` when using PyTorch/XLA. To silence this warning, `pip uninstall -y tensorflow && pip install tensorflow-cpu`. If you are in a notebook environment such as Colab or Kaggle, restart your notebook runtime afterwards.
  warnings.warn(
Checking input data.
Running predictions for 1 structure
Processing input data.
  0% 0/1 [00:00<?, ?it/s]Generating MSA for test_18b28/test_18b28.fasta with 1 protein entities.
100% 1/1 [00:00<00:00, 14.19it/s]
Traceback (most recent call last):
  File "/usr/local/bin/boltz", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/boltz/main.py", line 604, in predict
    trainer = Trainer(
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/utilities/argparse.py", line 70, in insert_env_defaults
    return fn(self, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/trainer.py", line 395, in __init__
    self._accelerator_connector = _AcceleratorConnector(
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 146, in __init__
    self._set_parallel_devices_and_init_accelerator()
  File "/usr/local/lib/python3.10/dist-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 359, in _set_parallel_devices_and_init_accelerator
    self.accelerator = AcceleratorRegistry.get(self._accelerator_flag)
  File "/usr/local/lib/python3.10/dist-packages/lightning_fabric/accelerators/registry.py", line 97, in get
    return data["accelerator"](**data["init_params"])
  File "/usr/local/lib/python3.10/dist-packages/lightning_fabric/accelerators/xla.py", line 36, in __init__
    if not _using_pjrt():
  File "/usr/local/lib/python3.10/dist-packages/lightning_fabric/accelerators/xla.py", line 112, in _using_pjrt
    return xr.using_pjrt()
AttributeError: module 'torch_xla.runtime' has no attribute 'using_pjrt'

What should I do?

**Comment by gcorso** [comment] 2024-11-30 15:07
This seems to be an issue with PyTorch Lightning: https://github.com/Lightning-AI/pytorch-lightning/issues/20419 
According to the comments on that issue they will push an update to fix it within the next week or so (at which point you should probably try to update lightning).

**Comment by gcorso** [comment] 2024-12-27 16:25
Closing this for now, please reopen if needed!

**Closed by gcorso** 2024-12-27 16:25 UTC

**Comment by kajiwara-riki** [comment] 2025-05-03 08:31
Hello. I’m trying to run **Boltz-1 on a TPU** as well.
Following the steps below I can make `main.py` start, so the standard inference pipeline *launches*, but it doesn’t appear to work correctly: TPU duty-cycle stays extremely low, TPU memory creeps upward as if there is a leak, and after a few hours the process ends abnormally with the message **`killed`**.

Is TPU execution officially supported for Boltz-1? If anyone has succeeded in running on TPU, I’d really appreciate your advice.

### Test environment

| Item           | Value                           |
| -------------- | ------------------------------- |
| TPU VM         | **v6e-1** (44 vCPU, 172 GB RAM) |
| Instance image | **v2-alpha-tpuv6e**             |
| Python         | 3.10                            |
| PyTorch        | 2.6.0                           |
| torch-xla      | 2.6.0                           |
| Boltz version  | 734cc2e                         |

### Environment setup

```bash
sudo apt update
sudo apt install -y libopenblas-base
sudo apt install python3.10-venv

pip3 install torch~=2.6.0 "torch_xla[tpu]~=2.6.0" \
     -f https://storage.googleapis.com/libtpu-releases/index.html \
     -f https://storage.googleapis.com/libtpu-wheels/index.html
```

### Boltz installation and hot-fix

```bash
git clone https://github.com/jwohlwend/boltz.git
```

Apply this hot-fix to **`src/boltz/main.py`** (L727) to prevent Trifast from being selected when no GPU is present:

```diff
- pairformer_args = PairformerArgs(use_trifast=(accelerator != "cpu"))
- msa_module_args = MSAModuleArgs(use_trifast=(accelerator != "cpu"))
+ pairformer_args = PairformerArgs(use_trifast=(accelerator == "gpu"))
+ msa_module_args = MSAModuleArgs(use_trifast=(accelerator == "gpu"))
```

```bash
pip install -e .        # install Boltz from source
pip uninstall trifast   # avoid NVIDIA-driver check during import
```

Boltz pins **pytorch-lightning == 2.4.0**; on XLA devices, but this can hit
[https://github.com/Lightning-AI/pytorch-lightning/issues/20419](https://github.com/Lightning-AI/pytorch-lightning/issues/20419),
so I upgrade:

```bash
pip install -U pytorch-lightning
```

`tpu-info` is optional but handy:

```bash
pip install tpu-info
```

### Reproduction command

```bash
python -m boltz.main predict examples/prot.yaml \
       --accelerator tpu --use_msa_server
```

After a long wait the process terminates with `killed`.
Excerpt of console log:

```
...
Downloading the CCD dictionary to /home/XXXXXXX/.boltz/ccd.pkl. You may change the cache directory with the --cache flag.
Downloading the model weights to /home/XXXXXXX/.boltz/boltz1_conf.ckpt. You may change the cache directory with the --cache flag.
Checking input data.
Running predictions for 1 structure
Processing input data.
  0%|                                                                                                                                                                                                                        | 0/1 [00:00<?, ?it/s]
Generating MSA for prot.yaml with 1 protein entities.
COMPLETE: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 150/150 [elapsed: 00:00 remaining: 00:00]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.03s/it]
WARNING:root:libtpu.so and TPU device found. Setting PJRT_DEVICE=TPU.
Using default `ModelCheckpoint`. Consider installing `litmodels` package to enable `LitModelCheckpoint` for automatic upload to the Lightning model registry.
GPU available: False, used: False
TPU available: True, using: 1 TPU cores
HPU available: False, using: 0 HPUs
/home/XXXXXXX/boltz-env/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/logger_connector/logger_connector.py:76: Starting from v1.9.0, `tensorboardX` has been removed as a dependency of the `pytorch_lightning` package, 
due to potential conflicts with other packages in the ML ecosystem. For this reason, `logger=True` will use `CSVLogger` as the default logger, unless the `tensorboard` or `tensorboardX` packages are found. Please `pip install lightning[extra]`
 or one of them to enable TensorBoard support by default
Predicting DataLoader 0:   0%|                                                                                                                                                                                               | 0/1 [00:00<?, ?it/s]killed
```

`tpu-info` in a second shell shows almost idle utilisation and only \~2 GiB of the 31 GiB memory in use, yet the memory figure rises slowly until the kill:

```
(boltz-env) XXXXXXX@t1v-n-37392f9a-w-0:~$ tpu-info
TPU Chips                                       
┏━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━┓
┃ Chip        ┃ Type         ┃ Devices ┃ PID   ┃
┡━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━┩
│ /dev/vfio/0 │ TPU v6e chip │ 1       │ 47124 │
└─────────────┴──────────────┴─────────┴───────┘
Connected to libtpu at grpc://localhost:8431...
TPU Utilization                               
┏━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ Device ┃ Memory usage         ┃ Duty cycle ┃
┡━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│ 0      │ 2.22 GiB / 31.25 GiB │      0.00% │
└────────┴──────────────────────┴────────────┘
WARNING: Buffer Transfer Latency metrics unavailable. Did you start a MULTI_SLICE workload with `TPU_RUNTIME_METRICS_PORTS=8431,8432,8433,8434`?
TPU Buffer Transfer Latency             
┏━━━━━━━━━━━━━┳━━━━━┳━━━━━┳━━━━━┳━━━━━━┓
┃ Buffer Size ┃ P50 ┃ P90 ┃ P95 ┃ P999 ┃
┡━━━━━━━━━━━━━╇━━━━━╇━━━━━╇━━━━━╇━━━━━━┩
└─────────────┴─────┴─────┴─────┴──────┘
```

### Additional info

- I tested torch / torch_xla versions from 2.5.0 up to 2.7.0, but the behavior did not change.
- Switching the hardware to a v5p TPU produced the same symptoms.

**Comment by andysw90** [comment] 2025-10-30 00:24
Did you ever find a fix for this?

**Comment by kajiwara-riki** [comment] 2025-11-07 05:23
Thank you for your response.
With updates including the torch_xla version upgrade and the removal of the trifast module dependency, I was able to confirm that the above procedure can be reproduced without the Hotfix. However, inference of Boltz-1 using TPU still cannot be executed even with the latest codebase (cb04aeccdd480fd4db707f0bbafde538397fa2ac), and the situation where it hangs at:
> Predicting DataLoader 0:   0%|                                                                                                                                                                                               | 0/1 [00:00<?, ?it/s]
has not been resolved.

Has anyone successfully run Boltz inference using TPU? Also, is TPU support officially confirmed?
I am considering using TPU to explore whether inference cost reduction and speedup are possible. Since execution on GPU works without any issues, this is not a high priority, but I would appreciate any insights or feedback you might have.

If I need to open a new issue, I'll create one!
